//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConClient.SessionServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SessionServiceReference.IConService")]
    public interface IConService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConService/Status", ReplyAction="http://tempuri.org/IConService/StatusResponse")]
        string Status();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConService/Status", ReplyAction="http://tempuri.org/IConService/StatusResponse")]
        System.Threading.Tasks.Task<string> StatusAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConServiceChannel : ConClient.SessionServiceReference.IConService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConServiceClient : System.ServiceModel.ClientBase<ConClient.SessionServiceReference.IConService>, ConClient.SessionServiceReference.IConService {
        
        public ConServiceClient() {
        }
        
        public ConServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Status() {
            return base.Channel.Status();
        }
        
        public System.Threading.Tasks.Task<string> StatusAsync() {
            return base.Channel.StatusAsync();
        }
    }
}
