//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientVersion1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="OperationA", ReplyAction="http://tempuri.org/IService/OperationAResponse")]
        string OperationA();
        
        [System.ServiceModel.OperationContractAttribute(Action="OperationA", ReplyAction="http://tempuri.org/IService/OperationAResponse")]
        System.Threading.Tasks.Task<string> OperationAAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="OperationB", ReplyAction="http://tempuri.org/IService/OperationBResponse")]
        string OperationB();
        
        [System.ServiceModel.OperationContractAttribute(Action="OperationB", ReplyAction="http://tempuri.org/IService/OperationBResponse")]
        System.Threading.Tasks.Task<string> OperationBAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : ClientVersion1.ServiceReference1.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<ClientVersion1.ServiceReference1.IService>, ClientVersion1.ServiceReference1.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string OperationA() {
            return base.Channel.OperationA();
        }
        
        public System.Threading.Tasks.Task<string> OperationAAsync() {
            return base.Channel.OperationAAsync();
        }
        
        public string OperationB() {
            return base.Channel.OperationB();
        }
        
        public System.Threading.Tasks.Task<string> OperationBAsync() {
            return base.Channel.OperationBAsync();
        }
    }
}
