//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoutingClient.PrintService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PrintService.IPrintService")]
    public interface IPrintService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrintService/Print", ReplyAction="http://tempuri.org/IPrintService/PrintResponse")]
        void Print(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrintService/Print", ReplyAction="http://tempuri.org/IPrintService/PrintResponse")]
        System.Threading.Tasks.Task PrintAsync(string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPrintServiceChannel : RoutingClient.PrintService.IPrintService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PrintServiceClient : System.ServiceModel.ClientBase<RoutingClient.PrintService.IPrintService>, RoutingClient.PrintService.IPrintService {
        
        public PrintServiceClient() {
        }
        
        public PrintServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PrintServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrintServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrintServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Print(string message) {
            base.Channel.Print(message);
        }
        
        public System.Threading.Tasks.Task PrintAsync(string message) {
            return base.Channel.PrintAsync(message);
        }
    }
}
