//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NinjaDomain.OldStyleContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;

    
    public partial class NinjaObjectContext : ObjectContext //changed from DbContext
    {
        public NinjaObjectContext()
            : base("name=NinjaObjectContext")
        {
            //initialize ObjectSets
            this.Clans = this.CreateObjectSet<Clan>();
            this.NinjaEquipments = this.CreateObjectSet<NinjaEquipment>();
            this.Ninjas = this.CreateObjectSet<Ninja>();
        }
    
        //Object Context doesn't use this
        //protected override void OnModelCreating(DbModelBuilder modelBuilder)
        //{
        //    throw new UnintentionalCodeFirstException();
        //}

        //Use ObjectSet instead of DbSet
        public ObjectSet<Clan> Clans { get; set; }
        public ObjectSet<NinjaEquipment> NinjaEquipments { get; set; }
        public ObjectSet<Ninja> Ninjas { get; set; }
    }
}
